# Generated by Django 4.2.3 on 2023-08-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_rename_room_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='participants',
        ),
        migrations.AddField(
            model_name='recipe',
            name='edited',
            field=models.BooleanField(null=True),
        ),
    ]
